import 'package:flutter/material.dart';

Widget termsAndConditionsText(context) => SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Terms and Conditions for Coffee Leaf Disease Detection Mobile Application',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 18,
              ),
            ),
            SizedBox(height: 16),
            Text(
              '1. Purpose of the Application:',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
            Text(
              '   a. The Application is designed to assist users in detecting three kinds of coffee diseases on leaves.\n'
              '   b. The three kinds of coffee diseases that the Application focuses on are [insert names of the diseases].\n'
              '   c. The Application utilizes advanced image processing and machine learning techniques to analyze and classify images of coffee leaves.',
            ),
            SizedBox(height: 16),
            Text(
              '2. Free to Use:',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
            Text(
              '   a. The Application is provided free of charge and can be downloaded and used without any payment obligations.\n'
              '   b. The Application may contain optional in-app purchases or advertisements, but their usage is entirely at the discretion of the user.\n'
              '   c. The developer reserves the right to modify the pricing structure or introduce charges for certain features in the future. Any changes will be communicated to users in advance.',
            ),
            SizedBox(height: 16),
            Text(
              '3. Accuracy of Information:',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
            Text(
              '   a. While the Application aims to provide accurate disease detection results, it is important to note that the information provided by the Application is not guaranteed to be 100% accurate.\n'
              '   b. The detection results generated by the Application are based on image analysis and machine learning algorithms, which may produce false positives or false negatives.\n'
              '   c. Users are advised not to solely rely on the Application\'s detection results for making important decisions regarding their coffee crops. Consultation with qualified professionals is recommended.',
            ),
            SizedBox(height: 16),
            Text(
              '4. Image Usage and Privacy:',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
            Text(
              '   a. When using the Application, users have the option to upload images of coffee leaves for disease detection purposes.\n'
              '   b. The uploaded images may be stored and used by the developer to improve the Application\'s disease detection model, enhance its accuracy, and develop future updates.\n'
              '   c. The developer is committed to protecting user privacy and will handle the images and related data in accordance with applicable privacy laws and regulations. Please refer to the Application\'s privacy policy for more information.',
            ),
            // Repeat the same pattern for the remaining points
            SizedBox(height: 20),

            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                TextButton(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  child: const Text('Close'),
                ),
              ],
            ),
            // Add any additional text or widgets as needed for the rest of the terms and conditions
          ],
        ),
      ),
    );

TermsAndConditions(context) => showDialog<String>(
      context: context,
      builder: (BuildContext context) => Dialog(
        child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: termsAndConditionsText(context)
//           child: Column(
//             mainAxisSize: MainAxisSize.min,
//             mainAxisAlignment: MainAxisAlignment.center,
//             children: <Widget>[
//               // RichText(
//               //   text: TextSpan(
//               //     text: 'Hello ',
//               //     children: const <TextSpan>[
//               //       TextSpan(
//               //           text: 'bold',
//               //           style: TextStyle(fontWeight: FontWeight.bold)),
//               //       TextSpan(text: ' world!'),
//               //     ],
//               //   ),
//               // ),
//               Text(
//                   """Restart your router (optional but recommended to ensure the settings take effect).
// Start your Django server.
// In a web browser on a different device or network, enter your public IP address followed by the port number in the URL. For example, http://<your-public-ip>:8000/.
// If the Django backend is accessible, you should see your application's response in the browser."""),
//               const SizedBox(height: 15),
//               TextButton(
//                 onPressed: () {
//                   Navigator.pop(context);
//                 },
//                 child: const Text('Close'),
//               ),
//             ],
//           ),

            ),
      ),
    );
